### ISSUE TITLE
[Visão Geral] - conhecendo o projeto

### ISSUE THREAD

**Issue by RodriguesLs** [institutotim/zup-docs#2]
Boa tarde, senhores(as)!

Eu baixei o sistema ZUP completo e gostaria de saber se haveria a possibilidade de alguém que tenha trabalhado ou conheça bem esse projeto me dar uma visão geral sobre ele. Isso porque eu tive dificuldade de entender algumas funcionalidades e também gostaria de saber o intuito de se ter utilizado determinada tecnologia e não outra, coisas desse tipo. 

@photonauta35 @aksakalli @lynxnathan @vitor-kato

**Comment by thiagomiqueias** [comment]
Oi @RodriguesLs, você precisa de uma visão geral do ponto de vista funcional ou técnico?

Eu fui o responsável pelo parametrização/configuração da plataforma em grandes municípios há pouco mais de dois anos atrás, além de ter ministrado os treinamentos.

Os idealizadores da arquitetura e desenvolvimento da API foram @lynxnathan e @estevaoam.

**Comment by RodriguesLs** [comment]
> Oi @RodriguesLs, você precisa de uma visão geral do ponto de vista funcional ou técnico?
> 
> Eu fui o responsável pelo parametrização/configuração da plataforma em grandes municípios há pouco mais de dois anos atrás, além de ter ministrado os treinamentos.
> 
> Os idealizadores da arquitetura e desenvolvimento da API foram @lynxnathan e @estevaoam.

Então, uma visão funcional já ajudaria bastante!
A propósito, já agradeço a velocidade da resposta hahah'

**Comment by thiagomiqueias** [comment]
Cara, eu cheguei a produzir um _knowledge base_ funcional do projeto, vou verificar se os mantenedores do repo ainda possuem alguma URL pública disso. Também cheguei a produzir um vídeo dando overview do painel,mas isso ocorreu nas primeiras releases, muita coisa evoluiu, mas acho que dá para você ter uma visão boa, vou procurar.

No mais, também presto consultoria junto com o Nathan e Estevão para a plataforma como um todo. Se houver alguma iniciativa privada ou pública, pode contar com a gente.

Ate amanhã vou checar o que existe de material por aqui que pode ser compartilhado. :)

_p.s.: dessa vez a resposta não foi tão rápida assim... :P_

**Comment by RodriguesLs** [comment]
> Cara, eu cheguei a produzir um _knowledge base_ funcional do projeto, vou verificar se os mantenedores do repo ainda possuem alguma URL pública disso. Também cheguei a produzir um vídeo dando overview do painel,mas isso ocorreu nas primeiras releases, muita coisa evoluiu, mas acho que dá para você ter uma visão boa, vou procurar.
> 
> No mais, também presto consultoria junto com o Nathan e Estevão para a plataforma como um todo. Se houver alguma iniciativa privada ou pública, pode contar com a gente.
> 
> Ate amanhã vou checar o que existe de material por aqui que pode ser compartilhado. :)
> 
> _p.s.: dessa vez a resposta não foi tão rápida assim... :P_

Hahahah', genial, ficarei muito grato! Aliás, sobre a consultoria, como poderíamos conversar a nível de contratação, isso é possível? Se minha empresa de repente se interessasse por isso.

**Comment by thiagomiqueias** [comment]
@RodriguesLs desculpe a demora, mas vamos lá:

Existe um knowledge base no repo zup-docs que você pode compreender os conceitos básicos sobre os módulos e features do painel do ZUP, a URL é [esta aqui](https://institutotim.github.io/zup-docs/knowledge/home).

Eu encontrei um vídeo de quase 1h50 minutos que explico sobre as regras de negócios relacionado a cada feature do ZUP, mas é um material de um cliente que envolve informações que impossibilita eu compartilhar aqui na comunidade.

Quanto a consultoria, vi que você entrou em contato com o Estevão via e-mail, vou conversar contigo naquela thread, contudo se houver algo que eu possa contribuir aqui publicamente para ajudar a comunidade, só me avisar. :)
